public class JWTTest {
    
    // @Depricated
    // public static void jwtTestMethod()
    // {
    //     //String access_token = jwtapex.get_access_token();
    //     Http http = new Http();
    //     String body = '{ "creditsId": "bhDZAiA0XNVnEV8u1qoL", "contacts": [ { "company": "James B Nutter", "customParameters" :[{"name":"recidOrdgId", "value":"sampleId12"}], "firstName": "Chery3", "lastName": "Jones", "linkedInUrl": "https://www.linkedin.com/in/cheryl-jones-b58bb111", "companyEmail":"cheryl.jones@jbnutter.com", "mobilePhones":["+18169357690"] } ] }';
    //     HttpRequest request = new HttpRequest();
    //     request.setMethod('POST');
    //     request.setEndpoint('https://modigie-val-gateway-pjcfvhz2qq-uc.a.run.app/api/val/v1/linkedInUrlJobs?key=AIzaSyDlol0-ZaUln9pdHbZzOAZb1DEQyOHD9gc');
    //     request.setHeader('Content-Type','application/json');
    //     request.setHeader('Content-Length',String.valueOf(body.length()));
    //     //request.setHeader('Host','modigie-val-gateway-pjcfvhz2qq-uc.a.run.app');
    //     request.setHeader('Authorization','Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJjNDk1MzBlMWZmOTA4M2RkNWVlYWEwNmJlMmNlNDM3ZjQ5YzkwNWUiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL21vZGlnaWUtdmFsLWJhY2tlbmQtcGpjZnZoejJxcS11Yy5hLnJ1bi5hcHAiLCJhenAiOiJtb2RpZ2llLXNhbGVzZm9yY2UtYXBwLTNAbW9kaWdpZS1iZXZhbC1kZXYtMi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsImVtYWlsIjoibW9kaWdpZS1zYWxlc2ZvcmNlLWFwcC0zQG1vZGlnaWUtYmV2YWwtZGV2LTIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNTk4OTYzOTU1LCJpYXQiOjE1OTg5NjAzNTUsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbSIsInN1YiI6IjExMzA5NjY2ODEyMDYxMDAyMjM2NyJ9.IdcYibdAeCLph6VMBkR5NTF3W3GGDjuHL0fR6EWE9kRHqMvXr_YCYdwnj4yV5AMhmutw2SvGv8QL3hkWpUMcsiaSqXDrkItbBRPFatv_bXfREeZy5fq7Ms-2liLaygXJX3QCiZsOdyzhYQJFtMUYPkyc7lXyZkLS0s36t_q8KXzvGIrbADxvXOt0iW0tmIivRkb7wL2B8asMfAqDRd6UaUIxIXhNrnXZdwtNWR_Sw7NHQ8Duu7AnPJIiNmlAtMXFk2TtnRjEQIJSYVN_ARWEMNAJDvYMlPpkeCW-K4Pl7dR2vI3d4dW-MCqekfJjZ5KwOAmqx3r41oDDrRdGe16DKAA');
    //     request.setBody(body);
    //     HttpResponse response = http.send(request);
    //     if(response.getStatus()=='OK')
    //     {
    //     }
    //     else
    //     {
    //     }
    // }
    
}