public class testlistview {
    // public List<Lead> selAccLst{get;set;}
    // public List<String> selIdList{get;set;}
    // public String accIds{get;set;}
    
    // // Constructor

    // @Depricated
    // public testlistview(ApexPages.StandardSetController cntlr){
    //     selIdList = new List<String>();
    //     selAccLst = cntlr.getSelected(); //get selected records from account list view
    //     accIds = '';  
    //     for(Lead acc : selAccLst){
    //         accIds += acc.Id + ','; //build list of ids string concatenated with comma
    //         selIdList.add(acc.Id);
    //     }
    // } 
    
 /*   public String getAccountPagination() {
      //  return selIdList;
        return accIds;
   } */
}